#! /bin/sh

# autostart applications
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
$HOME/.config/polybar/launch.sh
# pgrep -x redshift > /dev/null || redshift -c ~/.config/redshift/redshift.conf &
~/.fehbg &
pgrep -x dunst > /dev/null || dunst &

# bspwm
bspc monitor -d I II III IV V

bspc config window_gap      12
bspc config top_padding	    24
bspc config border_width    0

bspc config automatic_scheme     longest_side
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action2 resize_side
bspc config pointer action2 resize_corner
bspc config pointer_action1 move

bspc rule -a kitty focus=on state=floating rectangle=600x400+660+340
bspc rule -a tiled state=tiled focus=on
bspc rule -a configs state=floating focus=on rectangle=760x700+620+200
bspc rule -a keys state=floating focus=on rectangle=1100x700+480+180
bspc rule -a dev -o desktop='I' state=tiled

bspc rule -a Firefox desktop='II' focus=on follow=on state=tiled
bspc rule -a obsidian desktop='III' focus=on follow=on state=tiled
bspc rule -a TelegramDesktop desktop='V' state=floating follow=off \
    rectangle=680x920+35+60 && telegram-desktop &

# tui apps
bspc rule -a spt -o desktop='V' state=floating rectangle=680x500+500+60 follow=off
bspc rule -a gotop -o desktop='V' state=floating rectangle=680x920+1200+60 follow=off
kitty --class gotop gotop --nvidia &
kitty --class spt spt &

# scratchpad
bspc rule -a scratchpad sticky=on state=floating locked=on hidden=on rectangle=600x400+660+340
xdotool search --class scratchpad windowkill
kitty --class scratchpad &

bspc rule -a feh state=floating

# debian GUI
bspc rule -a Pavucontrol state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Power-manager state=floating
bspc rule -a Thunar state=floating

