#! /bin/bash

# Initializes all configuration files
# TODO: Ensure all files have appropriate permissions

if [ -d $HOME/dotfiles ]; then
  mkdir $HOME/dotfiles && cd $HOME/dotfiles

for d in */ ;
do
  stow $d
done
