#! /bin/bash

# Run this setup script on a new env to configure env

sudo apt update && sudo apt upgrade && sudo apt autoremove

# Remove bloat, unused apps
sudo apt remove thunderbird

# Remove games

# Install packages
sudo apt install bspwm, sxhkd, nitrogren, compton, rofi, neofetch, telegram-desktop

cd ~/Downloads

# Google Chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb

# Bitwarden

wget https://github.com/bitwarden/cli/releases/download/v1.18.0/bw-linux-1.18.0.zip
unzip bw-linux-1.18.0.zip
sudo install bw /usr/local/bin/
