#! /bin/bash

# Run this setup script on a new env to configure

sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get autoremove

# Install packages
sudo apt-get -y install \
  git \
  bspwm \
  sxhkd \
  feh \
  rofi \
  polybar \
  neovim \
  > /dev/null


# Install further apps
cd ~/Downloads
# pfetch, gotop, picom, alacritty, bonsai

# Remove xfce from session startup
# Add bspwm sxhkd to session startup
# Add ~/.fehbg
