#! /bin/bash

# Run setup to handle all configuration files into home directory
# Ensure all files have appropriate permissions

if [ -d $HOME/dotfiles ]; then
  mkdir $HOME/dotfiles && cd $HOME/dotfiles

for d in */ ;
do
  stow $d
done
