#! /bin/sh

# Autostart applications
sxhkd &
picom &
$HOME/.config/polybar/launch.sh

# Set wallpaper
~/.fehbg &

# bspwm
bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		14

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action2 resize_side
bspc config pointer action2 resize_corner
bspc config pointer_action1 move

bspc rule -a Kitty desktop='I' focus=on follow=on
bspc rule -a Code desktop='II' focus=on follow=on  
bspc rule -a Firefox desktop='III' focus=on follow=on
bspc rule -a TelegramDesktop desktop='IV' focus=on follow=on state=floating rectangle=640x880+20+45

# bspc rule -a Kitty:gotop desktop='V' state=floating center=on
