#! /bin/sh

# Autostart applications
sxhkd &

$HOME/.config/polybar/launch.sh
~/.fehbg &

picom &

# bspwm
bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action2 resize_side
bspc config pointer action2 resize_corner
bspc config pointer_action1 move

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -a Alacitty desktop='^1' focus=on follow=on
bspc rule -a Code desktop='^2' focus=on follow=on  
bspc rule -a Firefox desktop='^3' focus=on follow=on

