#!/bin/sh

# NOTE: maintain changes in Ansible arch role

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

SXHKD_FIFO="/var/run/user/$(id -u)/sxhkd.fifo"
if [ ! -p "$SXHKD_FIFO" ]; then
    mkfifo "$SXHKD_FIFO"
fi

sxhkd -s "$SXHKD_FIFO" &
exec bspwm
