settings:
  keyb_path: "$HOME/dotfiles/dots/keyb/.config/keyb/custom.yml"
  debug: true
  reverse: false
  mouse: true
  search_mode: false
  sort_keys: false
  title: ""
  prompt: 'keys > '
  prompt_location: "top"
  placeholder: '...'
  prefix_sep: ;
  sep_width: 4
  margin: 1
  padding: 1
  border: normal
color:
  prompt: "#FFA066"
  cursor_fg: "#edb"
  cursor_bg: "236"
  filter_fg: "#FFA066"
  filter_bg: ""
  counter_fg: ""
  counter_bg: ""
  placeholder_fg: ""
  placeholder_bg: ""
  border_color: ""
keys:
  quit: q, ctrl+c, esc
  up: k, up
  down: j, down
  up_focus: ctrl+k
  down_focus: ctrl+j
  half_up: ctrl+u
  half_down: ctrl+d
  full_up: ctrl+b
  full_bottom: ctrl+f
  first_line: g
  last_line: G
  top: H
  middle: M
  bottom: L
  search: /, S
  clear_search: alt+d
  normal: esc
