---
- hosts: localhost
  become: true

  tasks:
    - name: Install zsh
      apt: pkg=zsh state=latest

    - name: Check if ohmyzsh exists
      stat:
        path: "~/.oh-my-zsh"
      register: omz_exists

    - block:
      - name: end playbook if omz exists
        debug:
          msg: "omz exists, ending play"
      - meta: end_host
      when: not omz_exists.stat.exists

    - name: Download ohmyzsh installer script
      get_url:
        url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: "/tmp/zsh-installer.sh"
        mode: 0755

    - name: Execute installer
      command: /tmp/zsh-installer.sh "" --unattended
      become: false

    - name: Clean Up
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - "/tmp/zsh-installer.sh"
        - "~/.zshrc.pre-oh-my-zsh"

