---
- hosts: localhost
  become: true

  tasks:
    - name: Check if kitty.app exists
      stat:
        path: ~/.local/kitty.app
      register: kitty_exists

    - block:
      - name: end playbook if kitty.app exists
        debug:
          msg: "kitty exists, ending play"
      - meta: end_host
      when: not kitty_exists.stat.exists

    - name: Download kitty installer
      get_url:
        url: https://sw.kovidgoyal.net/kitty/installer.sh
        dest: /tmp/kitty-installer.sh
        mode: 0755

    - name: Execute installer
      command: /tmp/kitty-installer.sh launch=n
      become: false

    - name: Add kitty to PATH
      block:
        - name: Ensure bin directory in .local
          file:
            path: "~/.local/bin/kitty"
            state: directory
        - name: Create symlink to bin
          file:
            src: "~/.local/kitty.app/bin/kitty"
            dest: "~/.local/bin/kitty"
            state: link
            force: true
      become: false

    - name: Enable kitty in menus
      block:
        - name: Install kitty.desktop file
          copy:
            src: "~/.local/kitty.app/share/applications/kitty.desktop"
            dest: "~/.local/share/applications/kitty.desktop"
        - name: Let kitty icon appear in rofi and menus
          lineinfile:
            path: "~/.local/share/applications/kitty.desktop"
            regexp: "Icon=kitty"
            line: "Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png"
      become: false

    - name: Clean Up
      file:
        path: /tmp/kitty-installer.sh
        state: absent
